language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install:
    - composer self-update
    - composer install --prefer-source

before_script:
    - sudo apt-get install php5-fpm
    - ./.travis/bin/install-apcu.sh
    - phpenv config-add .travis/php/$TRAVIS_PHP_VERSION.ini
    - phpenv config-add .travis/ext/apc.ini
    - phpenv config-add .travis/ext/opcache.ini

script:
    - phpunit --coverage-clover=coverage.clover

after_script:
    - ./.travis/bin/code-coverage.sh
