language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install:
    - composer self-update
    - composer install --prefer-source

before_script:
    - sudo apt-get install php5-fpm
    - mkdir -p /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d
    - echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo 'opcache.enable_cli = On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo 'apc.enabled = On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo 'apc.enable_cli = On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
    - phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
