language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install:
    - composer self-update
    - composer install

before_script:
    - sudo apt-get install php5-fpm

script:
    - phpunit
